// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcVvPOX8EHL_9Lv2VHTveKyQ4l_0-Pi9o',
    appId: '1:254766757558:web:9ecd7a129e5e0ad159d817',
    messagingSenderId: '254766757558',
    projectId: 'babysitter-booking-app',
    authDomain: 'babysitter-booking-app.firebaseapp.com',
    storageBucket: 'babysitter-booking-app.firebasestorage.app',
    measurementId: 'G-RMJ9WK824T',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUHPx0yg1lQh1R0n8OSE5oT0wtMjP3akA',
    appId: '1:254766757558:ios:7f0c7bff29f6e7cb59d817',
    messagingSenderId: '254766757558',
    projectId: 'babysitter-booking-app',
    storageBucket: 'babysitter-booking-app.firebasestorage.app',
    iosBundleId: 'com.example.babysitterBookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUHPx0yg1lQh1R0n8OSE5oT0wtMjP3akA',
    appId: '1:254766757558:ios:7f0c7bff29f6e7cb59d817',
    messagingSenderId: '254766757558',
    projectId: 'babysitter-booking-app',
    storageBucket: 'babysitter-booking-app.firebasestorage.app',
    iosBundleId: 'com.example.babysitterBookingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcVvPOX8EHL_9Lv2VHTveKyQ4l_0-Pi9o',
    appId: '1:254766757558:web:2280164372b7bd3a59d817',
    messagingSenderId: '254766757558',
    projectId: 'babysitter-booking-app',
    authDomain: 'babysitter-booking-app.firebaseapp.com',
    storageBucket: 'babysitter-booking-app.firebasestorage.app',
    measurementId: 'G-Z33K58HG17',
  );

}